<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class DeploymentRecordSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('deployment_records')->insert([
            [
                "code" => "NA001",
                "title" => "Biên bản triển khai 1",
                "project_id" => 1,
                "handover_date" => "2023-06-15",
                "handover_person" => "Kiên18",
                "receiver"  => "Kiênlv18",
                "status_id" => "22",
            ],
            [
                "code" => "NA002",
                "title" => "Biên bản triển khai 2",
                "project_id" => 2,
                "handover_date" => "2023-06-16",
                "handover_person" => "Kiên19",
                "receiver"  => "Kiênlv19",
                "status_id" => "23",
            ],
            [
                "code" => "NA003",
                "title" => "Biên bản triển khai 3",
                "project_id" => 3,
                "handover_date" => "2023-06-16",
                "handover_person" => "Kiên19",
                "receiver"  => "Kiênlv19",
                "status_id" => "24",
            ],
            [
                "code" => "NA004",
                "title" => "Biên bản triển khai 4",
                "project_id" => 4,
                "handover_date" => "2023-06-16",
                "handover_person" => "Kiên19",
                "receiver"  => "Kiênlv19",
                "status_id" => "25",
            ],
            [
                "code" => "NA005",
                "title" => "Biên bản triển khai 5",
                "project_id" => 5,
                "handover_date" => "2023-06-16",
                "handover_person" => "Kiên19",
                "receiver"  => "Kiênlv19",
                "status_id" => "22",
            ],
            [
                "code" => "NA058",
                "title" => "Biên bản triển khai 6",
                "project_id" => 6,
                "handover_date" => "2023-06-20",
                "handover_person" => "Kiên18",
                "receiver"  => "Kiênlv18",
                "status_id" => "23",
            ],
            [
                "code" => "NA007",
                "title" => "Biên bản triển khai 6",
                "project_id" => 6,
                "handover_date" => "2023-06-20",
                "handover_person" => "Kiên18",
                "receiver"  => "Kiênlv18",
                "status_id" => "24",
            ],
            [
                "code" => "NA008",
                "title" => "Biên bản triển khai 6",
                "project_id" => 6,
                "handover_date" => "2023-06-20",
                "handover_person" => "Kiên18",
                "receiver"  => "Kiênlv18",
                "status_id" => "25",
            ],
            [
                "code" => "NA009",
                "title" => "Biên bản triển khai 6",
                "project_id" => 6,
                "handover_date" => "2023-06-20",
                "handover_person" => "Kiên18",
                "receiver"  => "Kiênlv18",
                "status_id" => "22",
            ],
            [
                "code" => "NA010",
                "title" => "Biên bản triển khai 6",
                "project_id" => 6,
                "handover_date" => "2023-06-20",
                "handover_person" => "Kiên18",
                "receiver"  => "Kiênlv18",
                "status_id" => "23",
            ],
            [
                "code" => "NA011",
                "title" => "Biên bản triển khai 6",
                "project_id" => 6,
                "handover_date" => "2023-06-20",
                "handover_person" => "Kiên18",
                "receiver"  => "Kiênlv18",
                "status_id" => "24",
            ],
            [
                "code" => "NA012",
                "title" => "Biên bản triển khai 6",
                "project_id" => 6,
                "handover_date" => "2023-06-20",
                "handover_person" => "Kiên18",
                "receiver"  => "Kiênlv18",
                "status_id" => "25",
            ],
            [
                "code" => "NA013",
                "title" => "Biên bản triển khai 6",
                "project_id" => 6,
                "handover_date" => "2023-06-20",
                "handover_person" => "Kiên18",
                "receiver"  => "Kiênlv18",
                "status_id" => "22",
            ],
            [
                "code" => "NA014",
                "title" => "Biên bản triển khai 6",
                "project_id" => 6,
                "handover_date" => "2023-06-20",
                "handover_person" => "Kiên18",
                "receiver"  => "Kiênlv18",
                "status_id" => "23",
            ],
            [
                "code" => "NA015",
                "title" => "Biên bản triển khai 6",
                "project_id" => 6,
                "handover_date" => "2023-06-20",
                "handover_person" => "Kiên18",
                "receiver"  => "Kiênlv18",
                "status_id" => "24",
            ],
            [
                "code" => "NA016",
                "title" => "Biên bản triển khai 6",
                "project_id" => 6,
                "handover_date" => "2023-06-20",
                "handover_person" => "Kiên18",
                "receiver"  => "Kiênlv18",
                "status_id" => "25",
            ],
            [
                "code" => "NA017",
                "title" => "Biên bản triển khai 6",
                "project_id" => 6,
                "handover_date" => "2023-06-20",
                "handover_person" => "Kiên18",
                "receiver"  => "Kiênlv18",
                "status_id" => "22",
            ],
            [
                "code" => "NA018",
                "title" => "Biên bản triển khai 6",
                "project_id" => 6,
                "handover_date" => "2023-06-20",
                "handover_person" => "Kiên18",
                "receiver"  => "Kiênlv18",
                "status_id" => "23",
            ],
            [
                "code" => "NA019",
                "title" => "Biên bản triển khai 6",
                "project_id" => 6,
                "handover_date" => "2023-06-20",
                "handover_person" => "Kiên18",
                "receiver"  => "Kiênlv18",
                "status_id" => "24",
            ],
            [
                "code" => "NA020",
                "title" => "Biên bản triển khai 6",
                "project_id" => 6,
                "handover_date" => "2023-06-20",
                "handover_person" => "Kiên18",
                "receiver"  => "Kiênlv18",
                "status_id" => "25",
            ],
            [
                "code" => "NA021",
                "title" => "Biên bản triển khai 6",
                "project_id" => 6,
                "handover_date" => "2023-06-20",
                "handover_person" => "Kiên18",
                "receiver"  => "Kiênlv18",
                "status_id" => "22",
            ],
            [
                "code" => "NA022",
                "title" => "Biên bản triển khai 6",
                "project_id" => 6,
                "handover_date" => "2023-06-20",
                "handover_person" => "Kiên18",
                "receiver"  => "Kiênlv18",
                "status_id" => "23",
            ],
            [
                "code" => "NA023",
                "title" => "Biên bản triển khai 6",
                "project_id" => 6,
                "handover_date" => "2023-06-20",
                "handover_person" => "Kiên18",
                "receiver"  => "Kiênlv18",
                "status_id" => "24",
            ],
            [
                "code" => "NA024",
                "title" => "Biên bản triển khai 6",
                "project_id" => 6,
                "handover_date" => "2023-06-20",
                "handover_person" => "Kiên18",
                "receiver"  => "Kiênlv18",
                "status_id" => "25",
            ],
            [
                "code" => "NA025",
                "title" => "Biên bản triển khai 6",
                "project_id" => 6,
                "handover_date" => "2023-06-20",
                "handover_person" => "Kiên18",
                "receiver"  => "Kiênlv18",
                "status_id" => "22",
            ],
            [
                "code" => "NA026",
                "title" => "Biên bản triển khai 6",
                "project_id" => 6,
                "handover_date" => "2023-06-20",
                "handover_person" => "Kiên18",
                "receiver"  => "Kiênlv18",
                "status_id" => "23",
            ],
            [
                "code" => "NA027",
                "title" => "Biên bản triển khai 6",
                "project_id" => 6,
                "handover_date" => "2023-06-20",
                "handover_person" => "Kiên18",
                "receiver"  => "Kiênlv18",
                "status_id" => "24",
            ],
            [
                "code" => "NA028",
                "title" => "Biên bản triển khai 6",
                "project_id" => 6,
                "handover_date" => "2023-06-20",
                "handover_person" => "Kiên18",
                "receiver"  => "Kiênlv18",
                "status_id" => "25",
            ],
            [
                "code" => "NA029",
                "title" => "Biên bản triển khai 6",
                "project_id" => 6,
                "handover_date" => "2023-06-20",
                "handover_person" => "Kiên18",
                "receiver"  => "Kiênlv18",
                "status_id" => "22",
            ],
            [
                "code" => "NA030",
                "title" => "Biên bản triển khai 6",
                "project_id" => 6,
                "handover_date" => "2023-06-20",
                "handover_person" => "Kiên18",
                "receiver"  => "Kiênlv18",
                "status_id" => "23",
            ],
            [
                "code" => "NA031",
                "title" => "Biên bản triển khai 6",
                "project_id" => 6,
                "handover_date" => "2023-06-20",
                "handover_person" => "Kiên18",
                "receiver"  => "Kiênlv18",
                "status_id" => "25",
            ],
            [
                "code" => "NA032",
                "title" => "Biên bản triển khai 6",
                "project_id" => 6,
                "handover_date" => "2023-06-20",
                "handover_person" => "Kiên18",
                "receiver"  => "Kiênlv18",
                "status_id" => "22",
            ],
            [
                "code" => "NA033",
                "title" => "Biên bản triển khai 6",
                "project_id" => 6,
                "handover_date" => "2023-06-20",
                "handover_person" => "Kiên18",
                "receiver"  => "Kiênlv18",
                "status_id" => "23",
            ],
            [
                "code" => "NA034",
                "title" => "Biên bản triển khai 6",
                "project_id" => 6,
                "handover_date" => "2023-06-20",
                "handover_person" => "Kiên18",
                "receiver"  => "Kiênlv18",
                "status_id" => "24",
            ],
            [
                "code" => "NA035",
                "title" => "Biên bản triển khai 6",
                "project_id" => 6,
                "handover_date" => "2023-06-20",
                "handover_person" => "Kiên18",
                "receiver"  => "Kiênlv18",
                "status_id" => "25",
            ],
            [
                "code" => "NA036",
                "title" => "Biên bản triển khai 6",
                "project_id" => 6,
                "handover_date" => "2023-06-20",
                "handover_person" => "Kiên18",
                "receiver"  => "Kiênlv18",
                "status_id" => "22",
            ],
            [
                "code" => "NA037",
                "title" => "Biên bản triển khai 6",
                "project_id" => 6,
                "handover_date" => "2023-06-20",
                "handover_person" => "Kiên18",
                "receiver"  => "Kiênlv18",
                "status_id" => "23",
            ],
            [
                "code" => "NA038",
                "title" => "Biên bản triển khai 6",
                "project_id" => 6,
                "handover_date" => "2023-06-20",
                "handover_person" => "Kiên18",
                "receiver"  => "Kiênlv18",
                "status_id" => "24",
            ],
            [
                "code" => "NA039",
                "title" => "Biên bản triển khai 6",
                "project_id" => 6,
                "handover_date" => "2023-06-20",
                "handover_person" => "Kiên18",
                "receiver"  => "Kiênlv18",
                "status_id" => "25",
            ],
            [
                "code" => "NA040",
                "title" => "Biên bản triển khai 6",
                "project_id" => 6,
                "handover_date" => "2023-06-20",
                "handover_person" => "Kiên18",
                "receiver"  => "Kiênlv18",
                "status_id" => "22",
            ],
            [
                "code" => "NA041",
                "title" => "Biên bản triển khai 6",
                "project_id" => 6,
                "handover_date" => "2023-06-20",
                "handover_person" => "Kiên18",
                "receiver"  => "Kiênlv18",
                "status_id" => "23",
            ],
            [
                "code" => "NA042",
                "title" => "Biên bản triển khai 6",
                "project_id" => 6,
                "handover_date" => "2023-06-20",
                "handover_person" => "Kiên18",
                "receiver"  => "Kiênlv18",
                "status_id" => "24",
            ],
            [
                "code" => "NA043",
                "title" => "Biên bản triển khai 6",
                "project_id" => 6,
                "handover_date" => "2023-06-20",
                "handover_person" => "Kiên18",
                "receiver"  => "Kiênlv18",
                "status_id" => "25",
            ],
            [
                "code" => "NA044",
                "title" => "Biên bản triển khai 6",
                "project_id" => 6,
                "handover_date" => "2023-06-20",
                "handover_person" => "Kiên18",
                "receiver"  => "Kiênlv18",
                "status_id" => "22",
            ],
            [
                "code" => "NA045",
                "title" => "Biên bản triển khai 6",
                "project_id" => 6,
                "handover_date" => "2023-06-20",
                "handover_person" => "Kiên18",
                "receiver"  => "Kiênlv18",
                "status_id" => "23",
            ],
            [
                "code" => "NA046",
                "title" => "Biên bản triển khai 6",
                "project_id" => 6,
                "handover_date" => "2023-06-20",
                "handover_person" => "Kiên18",
                "receiver"  => "Kiênlv18",
                "status_id" => "24",
            ],
            [
                "code" => "NA047",
                "title" => "Biên bản triển khai 6",
                "project_id" => 6,
                "handover_date" => "2023-06-20",
                "handover_person" => "Kiên18",
                "receiver"  => "Kiênlv18",
                "status_id" => "25",
            ],
            [
                "code" => "NA048",
                "title" => "Biên bản triển khai 6",
                "project_id" => 6,
                "handover_date" => "2023-06-20",
                "handover_person" => "Kiên18",
                "receiver"  => "Kiênlv18",
                "status_id" => "22",
            ],
            [
                "code" => "NA049",
                "title" => "Biên bản triển khai 6",
                "project_id" => 6,
                "handover_date" => "2023-06-20",
                "handover_person" => "Kiên18",
                "receiver"  => "Kiênlv18",
                "status_id" => "23",
            ],
            [
                "code" => "NA0050",
                "title" => "Biên bản triển khai 6",
                "project_id" => 6,
                "handover_date" => "2023-06-20",
                "handover_person" => "Kiên18",
                "receiver"  => "Kiênlv18",
                "status_id" => "24",
            ],
            [
                "code" => "NA052",
                "title" => "Biên bản triển khai 6",
                "project_id" => 6,
                "handover_date" => "2023-06-20",
                "handover_person" => "Kiên18",
                "receiver"  => "Kiênlv18",
                "status_id" => "25",
            ],
            [
                "code" => "NA053",
                "title" => "Biên bản triển khai 6",
                "project_id" => 6,
                "handover_date" => "2023-06-20",
                "handover_person" => "Kiên18",
                "receiver"  => "Kiênlv18",
                "status_id" => "22",
            ],
            [
                "code" => "NA054",
                "title" => "Biên bản triển khai 6",
                "project_id" => 6,
                "handover_date" => "2023-06-20",
                "handover_person" => "Kiên18",
                "receiver"  => "Kiênlv18",
                "status_id" => "23",
            ],
            [
                "code" => "NA055",
                "title" => "Biên bản triển khai 6",
                "project_id" => 6,
                "handover_date" => "2023-06-20",
                "handover_person" => "Kiên18",
                "receiver"  => "Kiênlv18",
                "status_id" => "24",
            ],
            [
                "code" => "NA056",
                "title" => "Biên bản triển khai 6",
                "project_id" => 6,
                "handover_date" => "2023-06-20",
                "handover_person" => "Kiên18",
                "receiver"  => "Kiênlv18",
                "status_id" => "25",
            ],
            [
                "code" => "NA057",
                "title" => "Biên bản triển khai 6",
                "project_id" => 6,
                "handover_date" => "2023-06-20",
                "handover_person" => "Kiên18",
                "receiver"  => "Kiênlv18",
                "status_id" => "22",
            ],
            [
                "code" => "NA058",
                "title" => "Biên bản triển khai 6",
                "project_id" => 6,
                "handover_date" => "2023-06-20",
                "handover_person" => "Kiên18",
                "receiver"  => "Kiênlv18",
                "status_id" => "23",
            ],
            [
                "code" => "NA059",
                "title" => "Biên bản triển khai 6",
                "project_id" => 6,
                "handover_date" => "2023-06-20",
                "handover_person" => "Kiên18",
                "receiver"  => "Kiênlv18",
                "status_id" => "24",
            ],
            [
                "code" => "NA060",
                "title" => "Biên bản triển khai 6",
                "project_id" => 6,
                "handover_date" => "2023-06-20",
                "handover_person" => "Kiên18",
                "receiver"  => "Kiênlv18",
                "status_id" => "6",
            ],
        ]);
    }
}
