<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class DispatchSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('dispatches')->insert([
            [
                "code" => "CV001",
                "number" => "01/TBNW-2023",
                "name" => "Công văn, thông báo 01",
                "date" => "2023-06-22",
                "type" => 1,
                "project_id" => 1,
                "customer_id" => 1,
                "content" => "Thông báo về việc bảo trì tháng 6",
                "status_id" => "18",
                "sender" => "Nguyễn Văn A",
                "receiver" => "Nguyễn Văn B",
                "from_date" => "2023-06-22",
                "to_date" => "2023-06-25",
            ],
            [
                "code" => "CV002",
                "number" => "02/TBNW-2023",
                "name" => "Công văn, thông báo 02",
                "date" => "2023-06-22",
                "type" => 1,
                "project_id" => 2,
                "customer_id" => 2,
                "content" => "Thông báo về việc bảo trì tháng 6",
                "status_id" => "18",
                "sender" => "Nguyễn Văn C",
                "receiver" => "Nguyễn Văn D",
                "from_date" => "2023-06-22",
                "to_date" => "2023-06-25",
            ],
            [
                "code" => "CV003",
                "number" => "03/TBNW-2023",
                "name" => "Công văn, thông báo 03",
                "date" => "2023-06-22",
                "type" => 0,
                "project_id" => 3,
                "customer_id" => 3,
                "content" => "Thông báo về việc bảo trì tháng 6",
                "status_id" => "18",
                "sender" => "Nguyễn Văn E",
                "receiver" => "Nguyễn Văn F",
                "from_date" => "2023-06-22",
                "to_date" => "2023-06-25",
            ],
            [
                "code" => "CV004",
                "number" => "04/TBNW-2023",
                "name" => "Công văn, thông báo 04",
                "date" => "2023-06-22",
                "type" => 0,
                "project_id" => 4,
                "customer_id" => 4,
                "content" => "Thông báo về việc bảo trì tháng 6",
                "status_id" => "18",
                "sender" => "Nguyễn Văn G",
                "receiver" => "Nguyễn Văn H",
                "from_date" => "2023-06-22",
                "to_date" => "2023-06-25",
            ],
            [
                "code" => "CV005",
                "number" => "05/TBNW-2023",
                "name" => "Công văn, thông báo 05",
                "date" => "2023-06-22",
                "type" => 1,
                "project_id" => 5,
                "customer_id" => 5,
                "content" => "Thông báo về việc bảo trì tháng 6",
                "status_id" => "18",
                "sender" => "Nguyễn Văn I",
                "receiver" => "Nguyễn Văn K",
                "from_date" => "2023-06-22",
                "to_date" => "2023-06-25",
            ],
            [
                "code" => "CV006",
                "number" => "CV006/TBNW-2023",
                "name" => "Công văn, thông báo 05",
                "date" => "2023-06-22",
                "type" => 1,
                "project_id" => 5,
                "customer_id" => 5,
                "content" => "Thông báo về việc bảo trì tháng 6",
                "status_id" => "18",
                "sender" => "Nguyễn Văn I",
                "receiver" => "Nguyễn Văn K",
                "from_date" => "2023-06-22",
                "to_date" => "2023-06-25",
            ],
            [
                "code" => "CV007",
                "number" => "CV007/TBNW-2023",
                "name" => "Công văn, thông báo 05",
                "date" => "2023-06-22",
                "type" => 1,
                "project_id" => 5,
                "customer_id" => 5,
                "content" => "Thông báo về việc bảo trì tháng 6",
                "status_id" => "18",
                "sender" => "Nguyễn Văn I",
                "receiver" => "Nguyễn Văn K",
                "from_date" => "2023-06-22",
                "to_date" => "2023-06-25",
            ],
            [
                "code" => "CV008",
                "number" => "CV008/TBNW-2023",
                "name" => "Công văn, thông báo 05",
                "date" => "2023-06-22",
                "type" => 1,
                "project_id" => 5,
                "customer_id" => 5,
                "content" => "Thông báo về việc bảo trì tháng 6",
                "status_id" => "16",
                "sender" => "Nguyễn Văn I",
                "receiver" => "Nguyễn Văn K",
                "from_date" => "2023-06-22",
                "to_date" => "2023-06-25",
            ],
            [
                "code" => "CV009",
                "number" => "CV009/TBNW-2023",
                "name" => "Công văn, thông báo 05",
                "date" => "2023-06-22",
                "type" => 1,
                "project_id" => 5,
                "customer_id" => 5,
                "content" => "Thông báo về việc bảo trì tháng 6",
                "status_id" => "16",
                "sender" => "Nguyễn Văn I",
                "receiver" => "Nguyễn Văn K",
                "from_date" => "2023-06-22",
                "to_date" => "2023-06-25",
            ],
            [
                "code" => "CV010",
                "number" => "CV010/TBNW-2023",
                "name" => "Công văn, thông báo 05",
                "date" => "2023-06-22",
                "type" => 1,
                "project_id" => 5,
                "customer_id" => 5,
                "content" => "Thông báo về việc bảo trì tháng 6",
                "status_id" => "16",
                "sender" => "Nguyễn Văn I",
                "receiver" => "Nguyễn Văn K",
                "from_date" => "2023-06-22",
                "to_date" => "2023-06-25",
            ],
            [
                "code" => "CV011",
                "number" => "CV011/TBNW-2023",
                "name" => "Công văn, thông báo 05",
                "date" => "2023-06-22",
                "type" => 1,
                "project_id" => 5,
                "customer_id" => 5,
                "content" => "Thông báo về việc bảo trì tháng 6",
                "status_id" => "16",
                "sender" => "Nguyễn Văn I",
                "receiver" => "Nguyễn Văn K",
                "from_date" => "2023-06-22",
                "to_date" => "2023-06-25",
            ],
            [
                "code" => "CV012",
                "number" => "CV012/TBNW-2023",
                "name" => "Công văn, thông báo 05",
                "date" => "2023-06-22",
                "type" => 1,
                "project_id" => 5,
                "customer_id" => 5,
                "content" => "Thông báo về việc bảo trì tháng 6",
                "status_id" => "16",
                "sender" => "Nguyễn Văn I",
                "receiver" => "Nguyễn Văn K",
                "from_date" => "2023-06-22",
                "to_date" => "2023-06-25",
            ],
            [
                "code" => "CV013",
                "number" => "CV013/TBNW-2023",
                "name" => "Công văn, thông báo 05",
                "date" => "2023-06-22",
                "type" => 1,
                "project_id" => 5,
                "customer_id" => 5,
                "content" => "Thông báo về việc bảo trì tháng 6",
                "status_id" => "16",
                "sender" => "Nguyễn Văn I",
                "receiver" => "Nguyễn Văn K",
                "from_date" => "2023-06-22",
                "to_date" => "2023-06-25",
            ],
            [
                "code" => "CV014",
                "number" => "CV014/TBNW-2023",
                "name" => "Công văn, thông báo 05",
                "date" => "2023-06-22",
                "type" => 1,
                "project_id" => 5,
                "customer_id" => 5,
                "content" => "Thông báo về việc bảo trì tháng 6",
                "status_id" => "16",
                "sender" => "Nguyễn Văn I",
                "receiver" => "Nguyễn Văn K",
                "from_date" => "2023-06-22",
                "to_date" => "2023-06-25",
            ],
            [
                "code" => "CV015",
                "number" => "CV015/TBNW-2023",
                "name" => "Công văn, thông báo 05",
                "date" => "2023-06-22",
                "type" => 1,
                "project_id" => 5,
                "customer_id" => 5,
                "content" => "Thông báo về việc bảo trì tháng 6",
                "status_id" => "16",
                "sender" => "Nguyễn Văn I",
                "receiver" => "Nguyễn Văn K",
                "from_date" => "2023-06-22",
                "to_date" => "2023-06-25",
            ],
            [
                "code" => "CV016",
                "number" => "CV016/TBNW-2023",
                "name" => "Công văn, thông báo 05",
                "date" => "2023-06-22",
                "type" => 1,
                "project_id" => 5,
                "customer_id" => 5,
                "content" => "Thông báo về việc bảo trì tháng 6",
                "status_id" => "16",
                "sender" => "Nguyễn Văn I",
                "receiver" => "Nguyễn Văn K",
                "from_date" => "2023-06-22",
                "to_date" => "2023-06-25",
            ],
            [
                "code" => "CV017",
                "number" => "CV017/TBNW-2023",
                "name" => "Công văn, thông báo 05",
                "date" => "2023-06-22",
                "type" => 1,
                "project_id" => 5,
                "customer_id" => 5,
                "content" => "Thông báo về việc bảo trì tháng 6",
                "status_id" => "16",
                "sender" => "Nguyễn Văn I",
                "receiver" => "Nguyễn Văn K",
                "from_date" => "2023-06-22",
                "to_date" => "2023-06-25",
            ],
            [
                "code" => "CV018",
                "number" => "CV018/TBNW-2023",
                "name" => "Công văn, thông báo 05",
                "date" => "2023-06-22",
                "type" => 1,
                "project_id" => 5,
                "customer_id" => 5,
                "content" => "Thông báo về việc bảo trì tháng 6",
                "status_id" => "16",
                "sender" => "Nguyễn Văn I",
                "receiver" => "Nguyễn Văn K",
                "from_date" => "2023-06-22",
                "to_date" => "2023-06-25",
            ],
            [
                "code" => "CV019",
                "number" => "CV019/TBNW-2023",
                "name" => "Công văn, thông báo 05",
                "date" => "2023-06-22",
                "type" => 1,
                "project_id" => 5,
                "customer_id" => 5,
                "content" => "Thông báo về việc bảo trì tháng 6",
                "status_id" => "16",
                "sender" => "Nguyễn Văn I",
                "receiver" => "Nguyễn Văn K",
                "from_date" => "2023-06-22",
                "to_date" => "2023-06-25",
            ],
            [
                "code" => "CV020",
                "number" => "CV020/TBNW-2023",
                "name" => "Công văn, thông báo 05",
                "date" => "2023-06-22",
                "type" => 1,
                "project_id" => 5,
                "customer_id" => 5,
                "content" => "Thông báo về việc bảo trì tháng 6",
                "status_id" => "16",
                "sender" => "Nguyễn Văn I",
                "receiver" => "Nguyễn Văn K",
                "from_date" => "2023-06-22",
                "to_date" => "2023-06-25",
            ],
            [
                "code" => "CV021",
                "number" => "CV021/TBNW-2023",
                "name" => "Công văn, thông báo 05",
                "date" => "2023-06-22",
                "type" => 1,
                "project_id" => 5,
                "customer_id" => 5,
                "content" => "Thông báo về việc bảo trì tháng 6",
                "status_id" => "16",
                "sender" => "Nguyễn Văn I",
                "receiver" => "Nguyễn Văn K",
                "from_date" => "2023-06-22",
                "to_date" => "2023-06-25",
            ],
            [
                "code" => "CV022",
                "number" => "CV022/TBNW-2023",
                "name" => "Công văn, thông báo 05",
                "date" => "2023-06-22",
                "type" => 1,
                "project_id" => 5,
                "customer_id" => 5,
                "content" => "Thông báo về việc bảo trì tháng 6",
                "status_id" => "16",
                "sender" => "Nguyễn Văn I",
                "receiver" => "Nguyễn Văn K",
                "from_date" => "2023-06-22",
                "to_date" => "2023-06-25",
            ],
            [
                "code" => "CV023",
                "number" => "CV023/TBNW-2023",
                "name" => "Công văn, thông báo 05",
                "date" => "2023-06-22",
                "type" => 1,
                "project_id" => 5,
                "customer_id" => 5,
                "content" => "Thông báo về việc bảo trì tháng 6",
                "status_id" => "16",
                "sender" => "Nguyễn Văn I",
                "receiver" => "Nguyễn Văn K",
                "from_date" => "2023-06-22",
                "to_date" => "2023-06-25",
            ],
            [
                "code" => "CV024",
                "number" => "CV024/TBNW-2023",
                "name" => "Công văn, thông báo 05",
                "date" => "2023-06-22",
                "type" => 1,
                "project_id" => 5,
                "customer_id" => 5,
                "content" => "Thông báo về việc bảo trì tháng 6",
                "status_id" => "16",
                "sender" => "Nguyễn Văn I",
                "receiver" => "Nguyễn Văn K",
                "from_date" => "2023-06-22",
                "to_date" => "2023-06-25",
            ],
            [
                "code" => "CV025",
                "number" => "CV025/TBNW-2023",
                "name" => "Công văn, thông báo 05",
                "date" => "2023-06-22",
                "type" => 1,
                "project_id" => 5,
                "customer_id" => 5,
                "content" => "Thông báo về việc bảo trì tháng 6",
                "status_id" => "16",
                "sender" => "Nguyễn Văn I",
                "receiver" => "Nguyễn Văn K",
                "from_date" => "2023-06-22",
                "to_date" => "2023-06-25",
            ],
            [
                "code" => "CV026",
                "number" => "CV026/TBNW-2023",
                "name" => "Công văn, thông báo 05",
                "date" => "2023-06-22",
                "type" => 1,
                "project_id" => 5,
                "customer_id" => 5,
                "content" => "Thông báo về việc bảo trì tháng 6",
                "status_id" => "16",
                "sender" => "Nguyễn Văn I",
                "receiver" => "Nguyễn Văn K",
                "from_date" => "2023-06-22",
                "to_date" => "2023-06-25",
            ],
            [
                "code" => "CV027",
                "number" => "CV027/TBNW-2023",
                "name" => "Công văn, thông báo 05",
                "date" => "2023-06-22",
                "type" => 1,
                "project_id" => 5,
                "customer_id" => 5,
                "content" => "Thông báo về việc bảo trì tháng 6",
                "status_id" => "16",
                "sender" => "Nguyễn Văn I",
                "receiver" => "Nguyễn Văn K",
                "from_date" => "2023-06-22",
                "to_date" => "2023-06-25",
            ],
            [
                "code" => "CV028",
                "number" => "CV028/TBNW-2023",
                "name" => "Công văn, thông báo 05",
                "date" => "2023-06-22",
                "type" => 1,
                "project_id" => 5,
                "customer_id" => 5,
                "content" => "Thông báo về việc bảo trì tháng 6",
                "status_id" => "17",
                "sender" => "Nguyễn Văn I",
                "receiver" => "Nguyễn Văn K",
                "from_date" => "2023-06-22",
                "to_date" => "2023-06-25",
            ],
            [
                "code" => "CV029",
                "number" => "CV029/TBNW-2023",
                "name" => "Công văn, thông báo 05",
                "date" => "2023-06-22",
                "type" => 1,
                "project_id" => 5,
                "customer_id" => 5,
                "content" => "Thông báo về việc bảo trì tháng 6",
                "status_id" => "17",
                "sender" => "Nguyễn Văn I",
                "receiver" => "Nguyễn Văn K",
                "from_date" => "2023-06-22",
                "to_date" => "2023-06-25",
            ],
            [
                "code" => "CV030",
                "number" => "CV030/TBNW-2023",
                "name" => "Công văn, thông báo 05",
                "date" => "2023-06-22",
                "type" => 1,
                "project_id" => 5,
                "customer_id" => 5,
                "content" => "Thông báo về việc bảo trì tháng 6",
                "status_id" => "17",
                "sender" => "Nguyễn Văn I",
                "receiver" => "Nguyễn Văn K",
                "from_date" => "2023-06-22",
                "to_date" => "2023-06-25",
            ],
            [
                "code" => "CV031",
                "number" => "CV031/TBNW-2023",
                "name" => "Công văn, thông báo 05",
                "date" => "2023-06-22",
                "type" => 1,
                "project_id" => 5,
                "customer_id" => 5,
                "content" => "Thông báo về việc bảo trì tháng 6",
                "status_id" => "17",
                "sender" => "Nguyễn Văn I",
                "receiver" => "Nguyễn Văn K",
                "from_date" => "2023-06-22",
                "to_date" => "2023-06-25",
            ],
            [
                "code" => "CV032",
                "number" => "CV032/TBNW-2023",
                "name" => "Công văn, thông báo 05",
                "date" => "2023-06-22",
                "type" => 1,
                "project_id" => 5,
                "customer_id" => 5,
                "content" => "Thông báo về việc bảo trì tháng 6",
                "status_id" => "17",
                "sender" => "Nguyễn Văn I",
                "receiver" => "Nguyễn Văn K",
                "from_date" => "2023-06-22",
                "to_date" => "2023-06-25",
            ],
            [
                "code" => "CV033",
                "number" => "CV033/TBNW-2023",
                "name" => "Công văn, thông báo 05",
                "date" => "2023-06-22",
                "type" => 1,
                "project_id" => 5,
                "customer_id" => 5,
                "content" => "Thông báo về việc bảo trì tháng 6",
                "status_id" => "17",
                "sender" => "Nguyễn Văn I",
                "receiver" => "Nguyễn Văn K",
                "from_date" => "2023-06-22",
                "to_date" => "2023-06-25",
            ],
            [
                "code" => "CV034",
                "number" => "CV034/TBNW-2023",
                "name" => "Công văn, thông báo 05",
                "date" => "2023-06-22",
                "type" => 1,
                "project_id" => 5,
                "customer_id" => 5,
                "content" => "Thông báo về việc bảo trì tháng 6",
                "status_id" => "17",
                "sender" => "Nguyễn Văn I",
                "receiver" => "Nguyễn Văn K",
                "from_date" => "2023-06-22",
                "to_date" => "2023-06-25",
            ],
            [
                "code" => "CV035",
                "number" => "CV035/TBNW-2023",
                "name" => "Công văn, thông báo 05",
                "date" => "2023-06-22",
                "type" => 1,
                "project_id" => 5,
                "customer_id" => 5,
                "content" => "Thông báo về việc bảo trì tháng 6",
                "status_id" => "17",
                "sender" => "Nguyễn Văn I",
                "receiver" => "Nguyễn Văn K",
                "from_date" => "2023-06-22",
                "to_date" => "2023-06-25",
            ],
            [
                "code" => "CV036",
                "number" => "CV036/TBNW-2023",
                "name" => "Công văn, thông báo 05",
                "date" => "2023-06-22",
                "type" => 1,
                "project_id" => 5,
                "customer_id" => 5,
                "content" => "Thông báo về việc bảo trì tháng 6",
                "status_id" => "17",
                "sender" => "Nguyễn Văn I",
                "receiver" => "Nguyễn Văn K",
                "from_date" => "2023-06-22",
                "to_date" => "2023-06-25",
            ],
            [
                "code" => "CV037",
                "number" => "CV037/TBNW-2023",
                "name" => "Công văn, thông báo 05",
                "date" => "2023-06-22",
                "type" => 1,
                "project_id" => 5,
                "customer_id" => 5,
                "content" => "Thông báo về việc bảo trì tháng 6",
                "status_id" => "17",
                "sender" => "Nguyễn Văn I",
                "receiver" => "Nguyễn Văn K",
                "from_date" => "2023-06-22",
                "to_date" => "2023-06-25",
            ],
            [
                "code" => "CV038",
                "number" => "CV038/TBNW-2023",
                "name" => "Công văn, thông báo 05",
                "date" => "2023-06-22",
                "type" => 1,
                "project_id" => 5,
                "customer_id" => 5,
                "content" => "Thông báo về việc bảo trì tháng 6",
                "status_id" => "17",
                "sender" => "Nguyễn Văn I",
                "receiver" => "Nguyễn Văn K",
                "from_date" => "2023-06-22",
                "to_date" => "2023-06-25",
            ],
            [
                "code" => "CV039",
                "number" => "CV039/TBNW-2023",
                "name" => "Công văn, thông báo 05",
                "date" => "2023-06-22",
                "type" => 1,
                "project_id" => 5,
                "customer_id" => 5,
                "content" => "Thông báo về việc bảo trì tháng 6",
                "status_id" => "17",
                "sender" => "Nguyễn Văn I",
                "receiver" => "Nguyễn Văn K",
                "from_date" => "2023-06-22",
                "to_date" => "2023-06-25",
            ],
            [
                "code" => "CV040",
                "number" => "CV040/TBNW-2023",
                "name" => "Công văn, thông báo 05",
                "date" => "2023-06-22",
                "type" => 1,
                "project_id" => 5,
                "customer_id" => 5,
                "content" => "Thông báo về việc bảo trì tháng 6",
                "status_id" => "17",
                "sender" => "Nguyễn Văn I",
                "receiver" => "Nguyễn Văn K",
                "from_date" => "2023-06-22",
                "to_date" => "2023-06-25",
            ],
            [
                "code" => "CV041",
                "number" => "CV041/TBNW-2023",
                "name" => "Công văn, thông báo 05",
                "date" => "2023-06-22",
                "type" => 1,
                "project_id" => 5,
                "customer_id" => 5,
                "content" => "Thông báo về việc bảo trì tháng 6",
                "status_id" => "17",
                "sender" => "Nguyễn Văn I",
                "receiver" => "Nguyễn Văn K",
                "from_date" => "2023-06-22",
                "to_date" => "2023-06-25",
            ],
            [
                "code" => "CV042",
                "number" => "CV042/TBNW-2023",
                "name" => "Công văn, thông báo 05",
                "date" => "2023-06-22",
                "type" => 1,
                "project_id" => 5,
                "customer_id" => 5,
                "content" => "Thông báo về việc bảo trì tháng 6",
                "status_id" => "17",
                "sender" => "Nguyễn Văn I",
                "receiver" => "Nguyễn Văn K",
                "from_date" => "2023-06-22",
                "to_date" => "2023-06-25",
            ],
            [
                "code" => "CV043",
                "number" => "CV043/TBNW-2023",
                "name" => "Công văn, thông báo 05",
                "date" => "2023-06-22",
                "type" => 1,
                "project_id" => 5,
                "customer_id" => 5,
                "content" => "Thông báo về việc bảo trì tháng 6",
                "status_id" => "17",
                "sender" => "Nguyễn Văn I",
                "receiver" => "Nguyễn Văn K",
                "from_date" => "2023-06-22",
                "to_date" => "2023-06-25",
            ],
            [
                "code" => "CV044",
                "number" => "CV044/TBNW-2023",
                "name" => "Công văn, thông báo 05",
                "date" => "2023-06-22",
                "type" => 1,
                "project_id" => 5,
                "customer_id" => 5,
                "content" => "Thông báo về việc bảo trì tháng 6",
                "status_id" => "17",
                "sender" => "Nguyễn Văn I",
                "receiver" => "Nguyễn Văn K",
                "from_date" => "2023-06-22",
                "to_date" => "2023-06-25",
            ],
            [
                "code" => "CV045",
                "number" => "CV045/TBNW-2023",
                "name" => "Công văn, thông báo 05",
                "date" => "2023-06-22",
                "type" => 1,
                "project_id" => 5,
                "customer_id" => 5,
                "content" => "Thông báo về việc bảo trì tháng 6",
                "status_id" => "17",
                "sender" => "Nguyễn Văn I",
                "receiver" => "Nguyễn Văn K",
                "from_date" => "2023-06-22",
                "to_date" => "2023-06-25",
            ],
            [
                "code" => "CV046",
                "number" => "CV046/TBNW-2023",
                "name" => "Công văn, thông báo 05",
                "date" => "2023-06-22",
                "type" => 1,
                "project_id" => 5,
                "customer_id" => 5,
                "content" => "Thông báo về việc bảo trì tháng 6",
                "status_id" => "17",
                "sender" => "Nguyễn Văn I",
                "receiver" => "Nguyễn Văn K",
                "from_date" => "2023-06-22",
                "to_date" => "2023-06-25",
            ],
            [
                "code" => "CV047",
                "number" => "CV047/TBNW-2023",
                "name" => "Công văn, thông báo 05",
                "date" => "2023-06-22",
                "type" => 1,
                "project_id" => 5,
                "customer_id" => 5,
                "content" => "Thông báo về việc bảo trì tháng 6",
                "status_id" => "17",
                "sender" => "Nguyễn Văn I",
                "receiver" => "Nguyễn Văn K",
                "from_date" => "2023-06-22",
                "to_date" => "2023-06-25",
            ],
            [
                "code" => "CV048",
                "number" => "CV048/TBNW-2023",
                "name" => "Công văn, thông báo 05",
                "date" => "2023-06-22",
                "type" => 1,
                "project_id" => 5,
                "customer_id" => 5,
                "content" => "Thông báo về việc bảo trì tháng 6",
                "status_id" => "18",
                "sender" => "Nguyễn Văn I",
                "receiver" => "Nguyễn Văn K",
                "from_date" => "2023-06-22",
                "to_date" => "2023-06-25",
            ],
            [
                "code" => "CV049",
                "number" => "CV049/TBNW-2023",
                "name" => "Công văn, thông báo 05",
                "date" => "2023-06-22",
                "type" => 1,
                "project_id" => 5,
                "customer_id" => 5,
                "content" => "Thông báo về việc bảo trì tháng 6",
                "status_id" => "18",
                "sender" => "Nguyễn Văn I",
                "receiver" => "Nguyễn Văn K",
                "from_date" => "2023-06-22",
                "to_date" => "2023-06-25",
            ],
            [
                "code" => "CV050",
                "number" => "CV050/TBNW-2023",
                "name" => "Công văn, thông báo 05",
                "date" => "2023-06-22",
                "type" => 1,
                "project_id" => 5,
                "customer_id" => 5,
                "content" => "Thông báo về việc bảo trì tháng 6",
                "status_id" => "18",
                "sender" => "Nguyễn Văn I",
                "receiver" => "Nguyễn Văn K",
                "from_date" => "2023-06-22",
                "to_date" => "2023-06-25",
            ],
            [
                "code" => "CV051",
                "number" => "CV051/TBNW-2023",
                "name" => "Công văn, thông báo 05",
                "date" => "2023-06-22",
                "type" => 1,
                "project_id" => 5,
                "customer_id" => 5,
                "content" => "Thông báo về việc bảo trì tháng 6",
                "status_id" => "18",
                "sender" => "Nguyễn Văn I",
                "receiver" => "Nguyễn Văn K",
                "from_date" => "2023-06-22",
                "to_date" => "2023-06-25",
            ],
            [
                "code" => "CV052",
                "number" => "CV052/TBNW-2023",
                "name" => "Công văn, thông báo 05",
                "date" => "2023-06-22",
                "type" => 1,
                "project_id" => 5,
                "customer_id" => 5,
                "content" => "Thông báo về việc bảo trì tháng 6",
                "status_id" => "18",
                "sender" => "Nguyễn Văn I",
                "receiver" => "Nguyễn Văn K",
                "from_date" => "2023-06-22",
                "to_date" => "2023-06-25",
            ],
            [
                "code" => "CV053",
                "number" => "CV053/TBNW-2023",
                "name" => "Công văn, thông báo 05",
                "date" => "2023-06-22",
                "type" => 1,
                "project_id" => 5,
                "customer_id" => 5,
                "content" => "Thông báo về việc bảo trì tháng 6",
                "status_id" => "18",
                "sender" => "Nguyễn Văn I",
                "receiver" => "Nguyễn Văn K",
                "from_date" => "2023-06-22",
                "to_date" => "2023-06-25",
            ],
            [
                "code" => "CV054",
                "number" => "CV054/TBNW-2023",
                "name" => "Công văn, thông báo 05",
                "date" => "2023-06-22",
                "type" => 1,
                "project_id" => 5,
                "customer_id" => 5,
                "content" => "Thông báo về việc bảo trì tháng 6",
                "status_id" => "18",
                "sender" => "Nguyễn Văn I",
                "receiver" => "Nguyễn Văn K",
                "from_date" => "2023-06-22",
                "to_date" => "2023-06-25",
            ],
            [
                "code" => "CV055",
                "number" => "CV055/TBNW-2023",
                "name" => "Công văn, thông báo 05",
                "date" => "2023-06-22",
                "type" => 1,
                "project_id" => 5,
                "customer_id" => 5,
                "content" => "Thông báo về việc bảo trì tháng 6",
                "status_id" => "18",
                "sender" => "Nguyễn Văn I",
                "receiver" => "Nguyễn Văn K",
                "from_date" => "2023-06-22",
                "to_date" => "2023-06-25",
            ],
            [
                "code" => "CV056",
                "number" => "CV056/TBNW-2023",
                "name" => "Công văn, thông báo 05",
                "date" => "2023-06-22",
                "type" => 1,
                "project_id" => 5,
                "customer_id" => 5,
                "content" => "Thông báo về việc bảo trì tháng 6",
                "status_id" => "18",
                "sender" => "Nguyễn Văn I",
                "receiver" => "Nguyễn Văn K",
                "from_date" => "2023-06-22",
                "to_date" => "2023-06-25",
            ],
            [
                "code" => "CV057",
                "number" => "CV057/TBNW-2023",
                "name" => "Công văn, thông báo 05",
                "date" => "2023-06-22",
                "type" => 1,
                "project_id" => 5,
                "customer_id" => 5,
                "content" => "Thông báo về việc bảo trì tháng 6",
                "status_id" => "18",
                "sender" => "Nguyễn Văn I",
                "receiver" => "Nguyễn Văn K",
                "from_date" => "2023-06-22",
                "to_date" => "2023-06-25",
            ],
            [
                "code" => "CV058",
                "number" => "CV058/TBNW-2023",
                "name" => "Công văn, thông báo 05",
                "date" => "2023-06-22",
                "type" => 1,
                "project_id" => 5,
                "customer_id" => 5,
                "content" => "Thông báo về việc bảo trì tháng 6",
                "status_id" => "18",
                "sender" => "Nguyễn Văn I",
                "receiver" => "Nguyễn Văn K",
                "from_date" => "2023-06-22",
                "to_date" => "2023-06-25",
            ],
            [
                "code" => "CV059",
                "number" => "CV059/TBNW-2023",
                "name" => "Công văn, thông báo 05",
                "date" => "2023-06-22",
                "type" => 1,
                "project_id" => 5,
                "customer_id" => 5,
                "content" => "Thông báo về việc bảo trì tháng 6",
                "status_id" => "18",
                "sender" => "Nguyễn Văn I",
                "receiver" => "Nguyễn Văn K",
                "from_date" => "2023-06-22",
                "to_date" => "2023-06-25",
            ],
            [
                "code" => "CV060",
                "number" => "CV060/TBNW-2023",
                "name" => "Công văn, thông báo 05",
                "date" => "2023-06-22",
                "type" => 1,
                "project_id" => 5,
                "customer_id" => 5,
                "content" => "Thông báo về việc bảo trì tháng 6",
                "status_id" => "18",
                "sender" => "Nguyễn Văn I",
                "receiver" => "Nguyễn Văn K",
                "from_date" => "2023-06-22",
                "to_date" => "2023-06-25",
            ],
        ]);
    }
}
