<?php

namespace Database\Seeders;

use App\Models\SystemFunction;
use DateTime;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;

class SystemFunctionSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {

        $functions = [
            [
                'id' => 1,
                'name' => 'Hệ thống',
                'code' => 'SYSTEM',
                'parent_id' => null,
                '_lft' => 1,
                '_rgt' => 45,
                'type' => 0,
            ],
            [
                'id' => 2,
                'name' => 'Quản lý người dùng',
                'code' => 'USER_MANAGEMENT',
                'parent_id' => 1,
                '_lft' => 2,
                '_rgt' => 24,
                'type' => 0,
            ],
            [
                'id' => 3,
                'name' => 'Khai báo nhóm quyền',
                'code' => 'DECLARE_ROLE',
                'parent_id' => 2,
                '_lft' => 3,
                '_rgt' => 12,
                'type' => 0,
            ],
            [
                'id' => 116,
                'name' => 'Xem nhóm quyền',
                'code' => 'VIEW_DECLARE_ROLE',
                'parent_id' => 3,
                'related_array_id' => "",
                'blocked_array_id' => "",
                // '_lft' => 4,
                // '_rgt' => 5,
                'type' => 0,
                'route_name' => 'admin.roles.index'
            ],
            [
                'id' => 4,
                'name' => 'Xem danh sách nhóm quyền',
                'code' => 'VIEW_LIST_DECLARE_ROLE',
                'related_array_id' => "[116]",
                // 'blocked_array_id' => "[103, 73]",
                'parent_id' => 3,
                // '_lft' => 4,
                // '_rgt' => 5,
                'type' => 0,
            ],
            [
                'id' => 5,
                'name' => 'Thêm nhóm quyền',
                'code' => 'ADD_DECLARE_ROLE',
                'related_array_id' => "[116]",
                'parent_id' => 3,
                // '_lft' => 6,
                // '_rgt' => 7,
                'type' => 0,
            ],
            [
                'id' => 6,
                'name' => 'Sửa nhóm quyền',
                'code' => 'EDIT_DECLARE_ROLE',
                'related_array_id' => "[116]",
                'parent_id' => 3,
                // '_lft' => 8,
                // '_rgt' => 9,
                'type' => 0,
            ],
            [
                'id' => 7,
                'name' => 'Xóa nhóm quyền',
                'code' => 'DELETE_DECLARE_ROLE',
                'related_array_id' => "[116]",
                'parent_id' => 3,
                // '_lft' => 10,
                // '_rgt' => 11,
                'type' => 0,
            ],
            [
                'id' => 8,
                'name' => 'Khai báo người dùng',
                'code' => 'USER',
                'parent_id' => 2,
                // '_lft' => 13,
                // '_rgt' => 24,
                'type' => 0,
            ],
            [
                'id' => 117,
                'name' => 'Xem người dùng',
                'code' => 'VIEW_USER',
                'parent_id' => 8,
                // '_lft' => 14,
                // '_rgt' => 15,
                'type' => 0,
                'status' => true,
                'is_role_menu' => 1,
                'route_name' => 'admin.users.index'
                // 'deleted_at' => new DateTime()
            ],
            [
                'id' => 9,
                'name' => 'Xem danh sách người dùng',
                'code' => 'VIEW_LIST_USER',
                'related_array_id' => "[117]",
                'parent_id' => 8,
                // '_lft' => 14,
                // '_rgt' => 15,
                'type' => 0,
                'status' => true,
                // 'deleted_at' => new DateTime()
            ],
            [
                'id' => 10,
                'name' => 'Thêm người dùng',
                'code' => 'ADD_USER',
                'related_array_id' => "[117]",
                'parent_id' => 8,
                // '_lft' => 16,
                // '_rgt' => 17,
                'type' => 0,
                'status' => true,
            ],
            [
                'id' => 11,
                'name' => 'Sửa người dùng',
                'code' => 'EDIT_USER',
                'related_array_id' => "[117]",
                'parent_id' => 8,
                // '_lft' => 18,
                // '_rgt' => 19,
                'type' => 0,
                'status' => true,
            ],
            [
                'id' => 12,
                'name' => 'Xóa người dùng',
                'code' => 'DELETE_USER',
                'related_array_id' => "[117]",
                'parent_id' => 8,
                // '_lft' => 20,
                // '_rgt' => 21,
                'type' => 0,
                'status' => true,
            ],
            [
                'id' => 13,
                'name' => 'Đổi mật khẩu',
                'code' => 'CHANGE_PASSWORD_USER',
                'related_array_id' => "[117]",
                'parent_id' => 8,
                // '_lft' => 22,
                // '_rgt' => 23,
                'type' => 0,
                'status' => true,
            ],
            /**
             * phân loại dự án _lft 25 --- _rgt 34 --- id 14 - 18
             */
            [
                'id' => 14,
                'name' => 'Quản lý phiếu yêu cầu',
                'code' => 'REQUEST_TICKETS',
                'parent_id' => 1,
                // '_lft' => 25,
                // '_rgt' => 34,
                'type' => 0,
                'status' => true,
            ],
            [
                'id' => 15,
                'name' => 'Xem phiếu yêu cầu',
                'code' => 'VIEW_REQUEST_TICKET',
                'parent_id' => 14,
                '_lft' => 26,
                '_rgt' => 27,
                'type' => 0,
                'status' => true,
                'is_role_menu' => 1,
                'route_name' => 'admin.request-tickets.index'
                // 'deleted_at' => new DateTime()
            ],
            [
                'id' => 16,
                'name' => 'Thêm mới phiếu yêu cầu',
                'code' => 'ADD_REQUEST_TICKET',
                'related_array_id' => "[15]",
                'parent_id' => 14,
                '_lft' => 28,
                '_rgt' => 29,
                'type' => 0,
                'status' => true,
            ],
            [
                'id' => 17,
                'name' => 'Sửa phiếu yêu cầu',
                'code' => 'EDIT_REQUEST_TICKET',
                'related_array_id' => "[15]",
                'parent_id' => 14,
                '_lft' => 30,
                '_rgt' => 31,
                'type' => 0,
                'status' => true,
            ],
            [
                'id' => 18,
                'name' => 'Xóa phiếu yêu cầu',
                'code' => 'DELETE_REQUEST_TICKET',
                'related_array_id' => "[15]",
                'parent_id' => 14,
                '_lft' => 32,
                '_rgt' => 33,
                'type' => 0,
                'status' => true,
            ],
            /**
             * khai báo trạng thái _lft 35--- _rgt 44 --- id 19 -
             */
            [
                'id' => 19,
                'name' => 'Quản lý quy trình duyệt',
                'code' => 'WORKFLOWS',
                'parent_id' => 1,
                '_lft' => 35,
                '_rgt' => 44,
                'type' => 0,
                'status' => true,
            ],
            [
                'id' => 20,
                'name' => 'Xem danh sách quy trình duyệt',
                'code' => 'VIEW_WORKFLOW',
                'parent_id' => 19,
                '_lft' => 36,
                '_rgt' => 37,
                'type' => 0,
                'status' => true,
                'is_role_menu' => 1,
                'route_name' => 'admin.workflow.index'
                // 'deleted_at' => new DateTime()
            ],
            [
                'id' => 21,
                'name' => 'Thêm mới quy trình duyệt',
                'code' => 'ADD_WORKFLOW',
                'related_array_id' => "[20]",
                'parent_id' => 19,
                '_lft' => 38,
                '_rgt' => 39,
                'type' => 0,
                'status' => true,
            ],
            [
                'id' => 22,
                'name' => 'Sửa quy trình duyệt',
                'code' => 'EDIT_WORKFLOW',
                'related_array_id' => "[20]",
                'parent_id' => 19,
                '_lft' => 40,
                '_rgt' => 41,
                'type' => 0,
                'status' => true,
            ],
            [
                'id' => 23,
                'name' => 'Xóa quy trình duyệt',
                'code' => 'DELETE_WORKFLOW',
                'related_array_id' => "[20]",
                'parent_id' => 19,
                '_lft' => 42,
                '_rgt' => 43,
                'type' => 0,
                'status' => true,
            ],
            // Chức năng của dự án
//            [
//                'id' => 24,
//                'name' => 'Thông tin dự án', // xem thông tin dự án
//                'code' => 'PROJECTS',
//                'parent_id' => null,
//                // '_lft' => 42,
//                // '_rgt' => 43,
//                'function_group' => 'Thông tin dự án',
//                'position' => 1,
//                'type' => 1,
//                'status' => true,
//            ],
//            [
//                'id' => 25,
//                'name' => 'Xem', // xem thông tin dự án
//                'code' => 'VIEW_PROJECT',
//                'parent_id' => 24,
//                // '_lft' => 42,
//                // '_rgt' => 43,
//                'function_group' => 'Thông tin dự án',
//                'type' => 1,
//                'status' => true,
//            ],
//            [
//                'id' => 26,
//                'name' => 'Sửa', // Sửa thông tin dự án
//                'code' => 'EDIT_PROJECT',
//                'parent_id' => 24,
//                'function_group' => 'Thông tin dự án',
//                'related_array_id' => "[25,27,28]",
//                // '_lft' => 42,
//                // '_rgt' => 43,
//                'type' => 1,
//                'status' => true,
//            ],
//            [
//                'id' => 27,
//                'name' => 'Xem SĐT Đại diện phía KH',
//                'code' => 'VIEW_PHONE_CUSTOMER_CONTACT',
//                'parent_id' => null,
//                'function_group' => 'Thông tin dự án',
//                'related_array_id' => "[25]",
//                'position' => 2,
//                // '_lft' => 42,
//                // '_rgt' => 43,
//                'type' => 1,
//                'status' => true,
//            ],
//            [
//                'id' => 28,
//                'name' => 'Xem Email Đại diện phía KH',
//                'code' => 'VIEW_EMAIL_CUSTOMER_CONTACT',
//                'parent_id' => null,
//                'function_group' => 'Thông tin dự án',
//                'related_array_id' => "[25]",
//                'position' => 3,
//                // '_lft' => 42,
//                // '_rgt' => 43,
//                'type' => 1,
//                'status' => true,
//            ],
//            [
//                'id' => 29,
//                'name' => 'Thông tin hợp đồng',
//                'code' => 'CONTRACTS',
//                'parent_id' => null,
//                'function_group' => 'Thông tin hợp đồng',
//                // '_lft' => 42,
//                // '_rgt' => 43,
//                'type' => 1,
//                'position' => 4,
//                'status' => true,
//            ],
//            [
//                'id' => 30,
//                'name' => 'Xem',
//                'code' => 'VIEW_CONTRACT',
//                'parent_id' => 29,
//                'related_array_id' => "[25]",
//                'function_group' => 'Thông tin hợp đồng',
//                // '_lft' => 42,
//                // '_rgt' => 43,
//                'type' => 1,
//                'status' => true,
//            ],
//            [
//                'id' => 31,
//                'name' => 'Thêm',
//                'code' => 'ADD_CONTRACT',
//                'parent_id' => 29,
//                'related_array_id' => "[30,25]",
//                'function_group' => 'Thông tin hợp đồng',
//                // '_lft' => 42,
//                // '_rgt' => 43,
//                'type' => 1,
//                'status' => true,
//            ],
//            [
//                'id' => 32,
//                'name' => 'Sửa',
//                'code' => 'EDIT_CONTRACT',
//                'parent_id' => 29,
//                'related_array_id' => "[30,25]",
//                'function_group' => 'Thông tin hợp đồng',
//                // '_lft' => 42,
//                // '_rgt' => 43,
//                'type' => 1,
//                'status' => true,
//            ],
//            [
//                'id' => 33,
//                'name' => 'Xóa',
//                'code' => 'DELETE_CONTRACT',
//                'parent_id' => 29,
//                'related_array_id' => "[30,25]",
//                'function_group' => 'Thông tin hợp đồng',
//                // '_lft' => 42,
//                // '_rgt' => 43,
//                'type' => 1,
//                'status' => true,
//            ],
//            [
//                'id' => 34,
//                'name' => 'Xem chi tiết số lần thanh toán',
//                'code' => 'VIEW_DETAIL_PAYMENT_CONTRACT',
//                'parent_id' => null,
//                'function_group' => 'Thông tin hợp đồng',
//                'related_array_id' => "[30,25]",
//                // '_lft' => 42,
//                // '_rgt' => 43,
//                'type' => 1,
//                'position' => 6,
//                'status' => true,
//            ],
//            [
//                'id' => 105,
//                'name' => 'Xem giá trị hợp đồng',
//                'code' => 'VIEW_PRICE_CONTRACT',
//                'parent_id' => null,
//                'function_group' => 'Thông tin hợp đồng',
//                'related_array_id' => "[30,25]",
//                // '_lft' => 42,
//                // '_rgt' => 43,
//                'type' => 1,
//                'position' => 5,
//                'status' => true,
//            ],
            // QUYỀN KHAI BÁO BÁO GIÁ
            [
                'id' => 95,
                'name' => 'Thông tin báo giá',
                'code' => 'PRICE_QUOTES',
                'parent_id' => NULL,
                'related_array_id' => null,
                'function_group' => 'Thông tin báo giá',
                'position' => 7,
                // '_lft' => 42,
                // '_rgt' => 43,
                'type' => 1,
                'status' => true,
            ],
            [
                'id' => 96,
                'name' => 'Xem',
                'code' => 'VIEW_PRICE_QUOTES',
                'parent_id' => 95,
                'related_array_id' => "[25,95]",
                'function_group' => 'Thông tin báo giá',
                // '_lft' => 42,
                // '_rgt' => 43,
                'type' => 1,
                'status' => true,
            ],
            [
                'id' => 97,
                'name' => 'Thêm',
                'code' => 'ADD_PRICE_QUOTES',
                'parent_id' => 95,
                'related_array_id' => "[96,25]",
                'function_group' => 'Thông tin báo giá',
                // '_lft' => 42,
                // '_rgt' => 43,
                'type' => 1,
                'status' => true,
            ],
            [
                'id' => 98,
                'name' => 'Sửa',
                'code' => 'EDIT_PRICE_QUOTES',
                'parent_id' => 95,
                'related_array_id' => "[25,96]",
                'function_group' => 'Thông tin báo giá',
                // '_lft' => 42,
                // '_rgt' => 43,
                'type' => 1,
                'status' => true,
            ],
            [
                'id' => 99,
                'name' => 'Xóa',
                'code' => 'DELETE_PRICE_QUOTES',
                'parent_id' => 95,
                'related_array_id' => "[25,96]",
                'function_group' => 'Thông tin báo giá',
                // '_lft' => 42,
                // '_rgt' => 43,
                'type' => 1,
                'status' => true,
            ],
            /**
             * Khai báo khách hàng _id = 35 -
             */
//            [
//                'id' => 35,
//                'name' => 'Khai báo khách hàng',
//                'code' => 'CUSTOMER',
//                'parent_id' => 1,
//                'function_group' => 'Khách hàng',
//                'related_array_id' => "",
//                // '_lft' => 42,
//                // '_rgt' => 43,
//                'type' => 0,
//                'status' => true,
//            ],
//            [
//                'id' => 108,
//                'name' => 'Xem khách hàng',
//                'code' => 'VIEW_CUSTOMER',
//                'parent_id' => 35,
//                'function_group' => 'Khách hàng',
//                'related_array_id' => "",
//                // '_lft' => 42,
//                // '_rgt' => 43,
//                'type' => 0,
//                'status' => true,
//                'is_role_menu' => 1,
//                'route_name' => 'admin.customers.view'
//                // 'deleted_at' => new DateTime()
//            ],
//            [
//                'id' => 36,
//                'name' => 'Xem danh sách khách hàng',
//                'code' => 'VIEW_LIST_CUSTOMER',
//                'parent_id' => 35,
//                'function_group' => 'Khách hàng',
//                'related_array_id' => "[108]",
//                // '_lft' => 42,
//                // '_rgt' => 43,
//                'type' => 0,
//                'status' => true,
//                'deleted_at' => new DateTime()
//            ],
//            [
//                'id' => 37,
//                'name' => 'Xem danh sách khách hàng VIP',
//                'code' => 'VIEW_LIST_CUSTOMER_VIP',
//                'parent_id' => 35,
//                'function_group' => 'Khách hàng',
//                'blocked_array_id' => "[41]",
//                'related_array_id' => "[108]",
//                // '_lft' => 42,
//                // '_rgt' => 43,
//                'type' => 0,
//                'status' => true,
//            ],
//            [
//                'id' => 38,
//                'name' => 'Thêm mới khách hàng',
//                'code' => 'ADD_CUSTOMER',
//                'parent_id' => 35,
//                'function_group' => 'Khách hàng',
//                'related_array_id' => "[108]",
//                'blocked_array_id' => "[41]",
//
//                // '_lft' => 42,
//                // '_rgt' => 43,
//                'type' => 0,
//                'status' => true,
//            ],
//            [
//                'id' => 39,
//                'name' => 'Sửa khách hàng',
//                'code' => 'EDIT_CUSTOMER',
//                'parent_id' => 35,
//                'function_group' => 'Khách hàng',
//                'related_array_id' => "[42, 43, 108]",
//                'blocked_array_id' => "[41]",
//
//                // '_lft' => 42,
//                // '_rgt' => 43,
//                'type' => 0,
//                'status' => true,
//            ],
//            [
//                'id' => 40,
//                'name' => 'Xóa khách hàng',
//                'code' => 'DELETE_CUSTOMER',
//                'parent_id' => 35,
//                'function_group' => 'Khách hàng',
//                'related_array_id' => "[108]",
//                'blocked_array_id' => "[41]",
//                // '_lft' => 42,
//                // '_rgt' => 43,
//                'type' => 0,
//                'status' => true,
//            ],
//            [
//                'id' => 41,
//                'name' => 'Thêm, sửa, xóa khách hàng VIP',
//                'code' => 'CUD_CUSTOMER_VIP',
//                'parent_id' => 35,
//                'function_group' => 'Khách hàng',
//                'related_array_id' => "[36, 37, 38, 39, 40, 42, 43, 108]",
//                // '_lft' => 42,
//                // '_rgt' => 43,
//                'type' => 0,
//                'status' => true,
//            ],
//            [
//                'id' => 42,
//                'name' => 'Xem người liên hệ',
//                'code' => 'VIEW_CUSTOMER_CONTACT',
//                'parent_id' => 35,
//                'function_group' => 'Khách hàng',
//                'related_array_id' => "[108]",
//                'blocked_array_id' => "[38, 39, 41]",
//                // '_lft' => 42,
//                // '_rgt' => 43,
//                'type' => 0,
//                'status' => true,
//            ],
//            [
//                'id' => 43,
//                'name' => 'Xem thông tin liên hệ',
//                'code' => 'VIEW_CUSTOMER_PHONE',
//                'parent_id' => 35,
//                'function_group' => 'Khách hàng',
//                'related_array_id' => "[108]",
//                'blocked_array_id' => "[38, 39, 41]",
//                // '_lft' => 42,
//                // '_rgt' => 43,
//                'type' => 0,
//                'status' => true,
//            ],
            [
                'id' => 72,
                'name' => 'Quản lý nhân sự',
                'code' => 'HRM_CONTACTS',
                'parent_id' => 1,
                'function_group' => 'dự án',
                'related_array_id' => "",
                // '_lft' => 42,
                // '_rgt' => 43,
                'type' => 0,
                'status' => true,
            ],
//            [
//                'id' => 118,
//                'name' => 'Xem danh sách nhân sự',
//                'code' => 'VIEW_HRM_CONTACT',
//                'parent_id' => 72,
//                'function_group' => 'dự án',
//                'related_array_id' => "",
//                'blocked_array_id' => "",
//                // '_lft' => 42,
//                // '_rgt' => 43,
//                'type' => 0,
//                'status' => true,
////                'is_role_menu' => 1,
//                'route_name' => 'admin.hrm-contacts.index'
//
//            ],
            [
                'id' => 73,
                'name' => 'Xem danh sách nhân sự',
                'code' => 'VIEW_HRM_CONTACT',
                'parent_id' => 72,
                'function_group' => 'dự án',
                'blocked_array_id' => "",
                // '_lft' => 42,
                // '_rgt' => 43,
                'type' => 0,
                'status' => true,
                'route_name' => 'admin.hrm-contacts.index'
            ],
            [
                'id' => 74,
                'name' => 'Thêm nhân sự',
                'code' => 'ADD_HRM_CONTACT',
                'parent_id' => 72,
                'function_group' => 'dự án',
                'related_array_id' => "[73]",
                // '_lft' => 42,
                // '_rgt' => 43,
                'type' => 0,
                'status' => true,
            ],
            [
                'id' => 127,
                'name' => 'Sửa nhân sự',
                'code' => 'EDIT_HRM_CONTACT',
                'parent_id' => 72,
                'function_group' => 'dự án',
                'related_array_id' => "[73]",
                // '_lft' => 42,
                // '_rgt' => 43,
                'type' => 0,
                'status' => true,
            ],
            [
                'id' => 128,
                'name' => 'Xóa nhân sự',
                'code' => 'DELETE_HRM_CONTACT',
                'parent_id' => 72,
                'function_group' => 'dự án',
                'related_array_id' => "[73]",
                // '_lft' => 42,
                // '_rgt' => 43,
                'type' => 0,
                'status' => true,
            ],
//            [
//                'id' => 132,
//                'name' => 'Phân quyền dự án',
//                'code' => 'SYSTEM_DECENTRALIZATION_PROJECT',
//                'parent_id' => 72,
//                'function_group' => 'dự án',
//                'related_array_id' => "[118, 73]",
//                // '_lft' => 42,
//                // '_rgt' => 43,
//                'type' => 0,
//                'status' => true,
//            ],
            [
                'id' => 102,
                'name' => 'Quản lý hợp đồng nhân sự',
                'code' => 'HRM_CONTRACT',
                'parent_id' => 1,
                'function_group' => 'hợp đồng',
                'related_array_id' => "[]",
                // '_lft' => 42,
                // '_rgt' => 43,
                'type' => 0,
                'status' => true,
            ],
//            [
//                'id' => 107,
//                'name' => 'Xem hợp đồng',
//                'code' => 'VIEW_MENU_CONTRACT',
//                'parent_id' => 102,
//                'function_group' => 'hợp đồng',
//                'related_array_id' => "",
//                // '_lft' => 42,
//                // '_rgt' => 43,
//                'type' => 0,
//                'status' => true,
//                'is_role_menu' => 1,
//                'route_name' => 'admin.contracts.index'
//            ],
            [
                'id' => 103,
                'name' => 'Xem danh sách hợp đồng nhân sự',
                'code' => 'VIEW_HRM_CONTRACT',
                'parent_id' => 102,
                'function_group' => 'hợp đồng',
                'related_array_id' => "",
                // '_lft' => 42,
                // '_rgt' => 43,
                'type' => 0,
                'status' => true,
                'route_name' => 'admin.hrm-contracts.index'
            ],
            [
                'id' => 129,
                'name' => 'Thêm mới hợp đồng nhân sự',
                'code' => 'ADD_HRM_CONTRACT',
                'parent_id' => 102,
                'function_group' => 'hợp đồng',
                'related_array_id' => "[103]",
                // '_lft' => 42,
                // '_rgt' => 43,
                'type' => 0,
                'status' => true,
            ],
            [
                'id' => 130,
                'name' => 'Sửa hợp đồng nhân sự',
                'code' => 'EDIT_HRM_CONTRACT',
                'parent_id' => 102,
                'function_group' => 'hợp đồng',
                'related_array_id' => "[103]",
                // '_lft' => 42,
                // '_rgt' => 43,
                'type' => 0,
                'status' => true,
            ],
            [
                'id' => 131,
                'name' => 'Xóa hợp đồng nhân sự',
                'code' => 'DELETE_HRM_CONTRACT',
                'parent_id' => 102,
                'function_group' => 'hợp đồng',
                'related_array_id' => "[103]",
                // '_lft' => 42,
                // '_rgt' => 43,
                'type' => 0,
                'status' => true,
            ],
            [
                'id' => 100,
                'name' => 'Báo giá sản phẩm',
                'code' => 'PRICE_QUOTE',
                'parent_id' => 1,
                'function_group' => 'báo giá sản phẩm',
                'related_array_id' => "",
                // '_lft' => 42,
                // '_rgt' => 43,
                'type' => 0,
                'status' => true,
            ],
            [
                'id' => 106,
                'name' => 'Xem báo giá sản phẩm',
                'code' => 'VIEW_PRICE_QUOTE',
                'parent_id' => 100,
                'function_group' => 'báo giá sản phẩm',
                'related_array_id' => "",
                // '_lft' => 42,
                // '_rgt' => 43,
                'type' => 0,
                'status' => true,
                'is_role_menu' => 1,
                'route_name' => 'admin.quote.view'
            ],
            [
                'id' => 133,
                'name' => 'Xem danh sách báo giá sản phẩm',
                'code' => 'VIEW_LIST_PRICE_QUOTE',
                'parent_id' => 100,
                'function_group' => 'báo giá sản phẩm',
                'related_array_id' => "[106]",
                // '_lft' => 42,
                // '_rgt' => 43,
                'type' => 0,
                'status' => true,
                'is_role_menu' => 1,
                'route_name' => 'admin.quote.view'
            ],
            [
                'id' => 134,
                'name' => 'Thêm báo giá sản phẩm',
                'code' => 'ADD_SYSTEM_PRICE_QUOTE',
                'parent_id' => 100,
                'function_group' => 'báo giá sản phẩm',
                'related_array_id' => "[73, 118, 106, 133]",
                // '_lft' => 42,
                // '_rgt' => 43,
                'type' => 0,
                'status' => true,
                'is_role_menu' => 1,
                'route_name' => 'admin.quote.view'
            ],
            [
                'id' => 135,
                'name' => 'Sửa báo giá sản phẩm',
                'code' => 'EDIT_SYSTEM_PRICE_QUOTE',
                'parent_id' => 100,
                'function_group' => 'báo giá sản phẩm',
                'related_array_id' => "[73, 118, 106, 133]",
                // '_lft' => 42,
                // '_rgt' => 43,
                'type' => 0,
                'status' => true,
                'is_role_menu' => 1,
                'route_name' => 'admin.quote.view'
            ],
            [
                'id' => 136,
                'name' => 'Xóa báo giá sản phẩm',
                'code' => 'DELETE_SYSTEM_PRICE_QUOTE',
                'parent_id' => 100,
                'function_group' => 'báo giá sản phẩm',
                'related_array_id' => "[73, 118, 106, 133]",
                // '_lft' => 42,
                // '_rgt' => 43,
                'type' => 0,
                'status' => true,
                'is_role_menu' => 1,
                'route_name' => 'admin.quote.view'
            ],
            [
                'id' => 101,
                'name' => 'Duyệt báo giá sản phẩm',
                'code' => 'APPROVE_PRICE_QUOTE',
                'parent_id' => 100,
                'function_group' => 'báo giá sản phẩm',
                'related_array_id' => "[73, 118, 106, 133]",
                // '_lft' => 42,
                // '_rgt' => 43,
                'type' => 0,
                'status' => true,
            ],
            [
                'id' => 44,
                'name' => 'Khai báo bộ phận',
                'code' => 'DEPARTMENT',
                'parent_id' => 1,
                'function_group' => 'Phòng ban - Bộ phận',
                'related_array_id' => "",
                // '_lft' => 42,
                // '_rgt' => 43,
                'type' => 0,
                'status' => true,
            ],
            [
                'id' => 109,
                'name' => 'Xem bộ phận',
                'code' => 'VIEW_DEPARTMENT',
                'parent_id' => 44,
                'function_group' => 'Phòng ban - Bộ phận',
                'related_array_id' => "",
                // '_lft' => 42,
                // '_rgt' => 43,
                'type' => 0,
                'status' => true,
                'is_role_menu' => 1,
                'route_name' => 'admin.departments.index'
            ],
            [
                'id' => 45,
                'name' => 'Thêm mới bộ phận',
                'code' => 'ADD_DEPARTMENT',
                'parent_id' => 44,
                'function_group' => 'Phòng ban - Bộ phận',
                'related_array_id' => "[109]",
                // '_lft' => 42,
                // '_rgt' => 43,
                'type' => 0,
                'status' => true,
            ],
            [
                'id' => 46,
                'name' => 'Sửa bộ phận',
                'code' => 'EDIT_DEPARTMENT',
                'parent_id' => 44,
                'function_group' => 'Phòng ban - Bộ phận',
                'related_array_id' => "[109]",
                // '_lft' => 42,
                // '_rgt' => 43,
                'type' => 0,
                'status' => true,
            ],
            [
                'id' => 47,
                'name' => 'Xóa bộ phận',
                'code' => 'DELETE_DEPARTMENT',
                'parent_id' => 44,
                'function_group' => 'Phòng ban - Bộ phận',
                'related_array_id' => "[109]",
                // '_lft' => 42,
                // '_rgt' => 43,
                'type' => 0,
                'status' => true,
            ],
            [
                'id' => 48,
                'name' => 'Khai báo loại hợp đồng',
                'code' => 'CONTRACT_TYPE',
                'parent_id' => 1,
                'function_group' => 'Loại hợp đồng',
                'related_array_id' => "",
                // '_lft' => 42,
                // '_rgt' => 43,
                'type' => 0,
                'status' => true,
            ],
            [
                'id' => 110,
                'name' => 'Xem loại hợp đồng',
                'code' => 'VIEW_CONTRACT_TYPE',
                'parent_id' => 48,
                'function_group' => 'Loại hợp đồng',
                'related_array_id' => "",
                // '_lft' => 42,
                // '_rgt' => 43,
                'type' => 0,
                'status' => true,
                'is_role_menu' => 1,
                'route_name' => 'admin.contract_type.view'
            ],
            [
                'id' => 49,
                'name' => 'Thêm mới loại hợp đồng',
                'code' => 'ADD_CONTRACT_TYPE',
                'parent_id' => 48,
                'function_group' => 'Loại hợp đồng',
                'related_array_id' => "[110]",
                // '_lft' => 42,
                // '_rgt' => 43,
                'type' => 0,
                'status' => true,
            ],
            [
                'id' => 50,
                'name' => 'Sửa loại hợp đồng',
                'code' => 'EDIT_CONTRACT_TYPE',
                'parent_id' => 48,
                'function_group' => 'Loại hợp đồng',
                'related_array_id' => "[110]",
                // '_lft' => 42,
                // '_rgt' => 43,
                'type' => 0,
                'status' => true,
            ],
            [
                'id' => 51,
                'name' => 'Xóa loại hợp đồng',
                'code' => 'DELETE_CONTRACT_TYPE',
                'parent_id' => 48,
                'function_group' => 'Loại hợp đồng',
                'related_array_id' => "[110]",
                // '_lft' => 42,
                // '_rgt' => 43,
                'type' => 0,
                'status' => true,
            ],
            [
                'id' => 52,
                'name' => 'Khai báo ngân hàng',
                'code' => 'BANK',
                'parent_id' => 1,
                'function_group' => 'ngân hàng',
                'related_array_id' => "",
                // '_lft' => 42,
                // '_rgt' => 43,
                'type' => 0,
                'status' => true,
            ],
            [
                'id' => 111,
                'name' => 'Xem ngân hàng',
                'code' => 'VIEW_BANK',
                'parent_id' => 52,
                'function_group' => 'ngân hàng',
                'related_array_id' => "",
                // '_lft' => 42,
                // '_rgt' => 43,
                'type' => 0,
                'status' => true,
                'is_role_menu' => 1,
                'route_name' => 'admin.banks.index'
            ],
            [
                'id' => 53,
                'name' => 'Thêm mới ngân hàng',
                'code' => 'ADD_BANK',
                'parent_id' => 52,
                'function_group' => 'ngân hàng',
                'related_array_id' => "[111]",
                // '_lft' => 42,
                // '_rgt' => 43,
                'type' => 0,
                'status' => true,
            ],
            [
                'id' => 54,
                'name' => 'Sửa ngân hàng',
                'code' => 'EDIT_BANK',
                'parent_id' => 52,
                'function_group' => 'ngân hàng',
                'related_array_id' => "[111]",
                // '_lft' => 42,
                // '_rgt' => 43,
                'type' => 0,
                'status' => true,
            ],
            [
                'id' => 55,
                'name' => 'Xóa ngân hàng',
                'code' => 'DELETE_BANK',
                'parent_id' => 52,
                'function_group' => 'ngân hàng',
                'related_array_id' => "[111]",
                // '_lft' => 42,
                // '_rgt' => 43,
                'type' => 0,
                'status' => true,
            ],
            [
                'id' => 56,
                'name' => 'Khai báo phụ cấp',
                'code' => 'ALLOWANCES',
                'parent_id' => 1,
                'function_group' => 'nhóm sản phẩm, dịch vụ',
                'related_array_id' => "",
                // '_lft' => 42,
                // '_rgt' => 43,
                'type' => 0,
                'status' => true,
            ],
            [
                'id' => 112,
                'name' => 'Xem danh sách phụ cấp',
                'code' => 'VIEW_ALLOWANCE',
                'parent_id' => 56,
                'function_group' => 'nhóm sản phẩm, dịch vụ',
                'related_array_id' => "",
                // '_lft' => 42,
                // '_rgt' => 43,
                'type' => 0,
                'status' => true,
                'is_role_menu' => 1,
                'route_name' => 'admin.allowances.index'
            ],
            [
                'id' => 57,
                'name' => 'Thêm mới phụ cấp',
                'code' => 'ADD_ALLOWANCE',
                'parent_id' => 56,
                'function_group' => 'nhóm sản phẩm, dịch vụ',
                'related_array_id' => "[112]",
                // '_lft' => 42,
                // '_rgt' => 43,
                'type' => 0,
                'status' => true,
            ],
            [
                'id' => 58,
                'name' => 'Sửa nhóm phụ cấp',
                'code' => 'EDIT_ALLOWANCE',
                'parent_id' => 56,
                'function_group' => 'nhóm sản phẩm, dịch vụ',
                'related_array_id' => "[112]",
                // '_lft' => 42,
                // '_rgt' => 43,
                'type' => 0,
                'status' => true,
            ],
            [
                'id' => 59,
                'name' => 'Xóa phụ cấp',
                'code' => 'DELETE_ALLOWANCE',
                'parent_id' => 56,
                'function_group' => 'nhóm sản phẩm, dịch vụ',
                'related_array_id' => "[112]",
                // '_lft' => 42,
                // '_rgt' => 43,
                'type' => 0,
                'status' => true,
            ],
            [
                'id' => 60,
                'name' => 'Khai báo thuế thu nhập cá nhân',
                'code' => 'TAXES',
                'parent_id' => 1,
                'function_group' => 'sản phẩm, dịch vụ',
                'related_array_id' => "",
                // '_lft' => 42,
                // '_rgt' => 43,
                'type' => 0,
                'status' => true,
            ],
            [
                'id' => 113,
                'name' => 'Xem danh sách thuế thu nhập cá nhân',
                'code' => 'VIEW_TAXES',
                'parent_id' => 60,
                'function_group' => 'sản phẩm, dịch vụ',
                'related_array_id' => "",
                // '_lft' => 42,
                // '_rgt' => 43,
                'type' => 0,
                'status' => true,
                'is_role_menu' => 1,
                'route_name' => 'admin.taxes.index'
            ],
            [
                'id' => 61,
                'name' => 'Thêm mới thuế thu nhập cá nhân',
                'code' => 'ADD_TAXES',
                'parent_id' => 60,
                'function_group' => 'sản phẩm, dịch vụ',
                'related_array_id' => "[113]",
                // '_lft' => 42,
                // '_rgt' => 43,
                'type' => 0,
                'status' => true,
            ],
            [
                'id' => 62,
                'name' => 'Sửa thuế thu nhập cá nhân',
                'code' => 'EDIT_TAXES',
                'parent_id' => 60,
                'function_group' => 'sản phẩm, dịch vụ',
                'related_array_id' => "[113]",
                // '_lft' => 42,
                // '_rgt' => 43,
                'type' => 0,
                'status' => true,
            ],
            [
                'id' => 63,
                'name' => 'Xóa thuế thu nhập cá nhân',
                'code' => 'DELETE_TAXES',
                'parent_id' => 60,
                'function_group' => 'sản phẩm, dịch vụ',
                'related_array_id' => "[113]",
                // '_lft' => 42,
                // '_rgt' => 43,
                'type' => 0,
                'status' => true,
            ],
            [
                'id' => 64,
                'name' => 'Qũy nội bộ',
                'code' => 'INTERNAL_FUND',
                'parent_id' => 1,
                'function_group' => 'đơn vị tính',
                'related_array_id' => "",
                // '_lft' => 42,
                // '_rgt' => 43,
                'type' => 0,
                'status' => true,
            ],
            [
                'id' => 114,
                'name' => 'Xem quỹ nội bộ',
                'code' => 'VIEW_INTERNAL_FUND',
                'parent_id' => 64,
                'function_group' => 'đơn vị tính',
                'related_array_id' => "",
                // '_lft' => 42,
                // '_rgt' => 43,
                'type' => 0,
                'status' => true,
                'is_role_menu' => 1,
                'route_name' => 'admin.internal-fund.index'
            ],
//            [
//                'id' => 65,
//                'name' => 'Thêm mới đơn vị tính',
//                'code' => 'ADD_UNIT',
//                'parent_id' => 64,
//                'function_group' => 'đơn vị tính',
//                'related_array_id' => "[114]",
//                // '_lft' => 42,
//                // '_rgt' => 43,
//                'type' => 0,
//                'status' => true,
//            ],
            [
                'id' => 66,
                'name' => 'Sửa quỹ nội bộ',
                'code' => 'EDIT_INTERNAL_FUND',
                'parent_id' => 64,
                'function_group' => 'đơn vị tính',
                'related_array_id' => "[114]",
                // '_lft' => 42,
                // '_rgt' => 43,
                'type' => 0,
                'status' => true,
            ],
//            [
//                'id' => 67,
//                'name' => 'Xóa đơn vị tính',
//                'code' => 'DELETE_UNIT',
//                'parent_id' => 64,
//                'function_group' => 'đơn vị tính',
//                'related_array_id' => "[114]",
//                // '_lft' => 42,
//                // '_rgt' => 43,
//                'type' => 0,
//                'status' => true,
//            ],
            [
                'id' => 68,
                'name' => 'Cấu hình nghỉ phép',
                'code' => 'USER_LEAVE_DAYS',
                'parent_id' => 1,
                'function_group' => 'tỉ lệ thuế phí',
                'related_array_id' => "",
                // '_lft' => 42,
                // '_rgt' => 43,
                'type' => 0,
                'status' => true,
            ],
            [
                'id' => 115,
                'name' => 'Xem cấu hình nghỉ phép',
                'code' => 'VIEW_USER_LEAVE_DAYS',
                'parent_id' => 68,
                'function_group' => 'tỉ lệ thuế phí',
                'related_array_id' => "",
                // '_lft' => 42,
                // '_rgt' => 43,
                'type' => 0,
                'status' => true,
                'is_role_menu' => 1,
                'route_name' => 'admin.user-leave-days.index'
            ],
//            [
//                'id' => 69,
//                'name' => 'Thêm mới tỉ lệ thuế phí',
//                'code' => 'ADD_TAX_FEE_RATE',
//                'parent_id' => 68,
//                'function_group' => 'tỉ lệ thuế phí',
//                'related_array_id' => "[115]",
//                // '_lft' => 42,
//                // '_rgt' => 43,
//                'type' => 0,
//                'status' => true,
//            ],
            [
                'id' => 70,
                'name' => 'Cập nhật cấu hình nghỉ phép',
                'code' => 'EDIT_USER_LEAVE_DAYS',
                'parent_id' => 68,
                'function_group' => 'tỉ lệ thuế phí',
                'related_array_id' => "[115]",
                // '_lft' => 42,
                // '_rgt' => 43,
                'type' => 0,
                'status' => true,
            ],
//            [
//                'id' => 71,
//                'name' => 'Xóa tỉ lệ thuế phí',
//                'code' => 'DELETE_TAX_FEE_RATE',
//                'parent_id' => 68,
//                'function_group' => 'tỉ lệ thuế phí',
//                'related_array_id' => "[115]",
//                // '_lft' => 42,
//                // '_rgt' => 43,
//                'type' => 0,
//                'status' => true,
//            ],
            [
                'id' => 75,
                'name' => 'Quản lý lịch triển khai',
                'code' => 'DEPLOYMENT_SCHEDULE',
                'parent_id' => 1,
                'function_group' => 'lịch triển khai',
                'related_array_id' => "",
                // '_lft' => 42,
                // '_rgt' => 43,
                'type' => 0,
                'status' => true,
            ],
            [
                'id' => 76,
                'name' => 'Xem lịch triển khai',
                'code' => 'VIEW_DEPLOYMENT_SCHEDULE',
                'parent_id' => 75,
                'function_group' => 'lịch triển khai',
                'related_array_id' => "",
                // '_lft' => 42,
                // '_rgt' => 43,
                'type' => 0,
                'status' => true,
                'is_role_menu' => 1,
                'route_name' => 'admin.deployment_schedule.index'
                // 'deleted_at' => new DateTime()
            ],
            [
                'id' => 77,
                'name' => 'Thêm mới lịch triển khai',
                'code' => 'ADD_DEPLOYMENT_SCHEDULE',
                'parent_id' => 75,
                'function_group' => 'lịch triển khai',
                'related_array_id' => "[76]",
                // '_lft' => 42,
                // '_rgt' => 43,
                'type' => 0,
                'status' => true,
            ],
            [
                'id' => 78,
                'name' => 'Sửa lịch triển khai',
                'code' => 'EDIT_DEPLOYMENT_SCHEDULE',
                'parent_id' => 75,
                'function_group' => 'lịch triển khai',
                'related_array_id' => "[76]",
                // '_lft' => 42,
                // '_rgt' => 43,
                'type' => 0,
                'status' => true,
            ],
            [
                'id' => 79,
                'name' => 'Xóa lịch triển khai',
                'code' => 'DELETE_DEPLOYMENT_SCHEDULE',
                'parent_id' => 75,
                'function_group' => 'lịch triển khai',
                'related_array_id' => "[76]",
                // '_lft' => 42,
                // '_rgt' => 43,
                'type' => 0,
                'status' => true,
            ],
            [
                'id' => 80,
                'name' => 'Quản lý biên bản triển khai dự án',
                'code' => 'DEPLOYMENT_RECORD',
                'parent_id' => 1,
                'function_group' => 'biên bản triển khai dự án',
                'related_array_id' => "",
                // '_lft' => 42,
                // '_rgt' => 43,
                'type' => 0,
                'status' => true,
            ],
            [
                'id' => 81,
                'name' => 'Xem biên bản triển khai dự án',
                'code' => 'VIEW_DEPLOYMENT_RECORD',
                'parent_id' => 80,
                'function_group' => 'biên bản triển khai dự án',
                'related_array_id' => "",
                // '_lft' => 42,
                // '_rgt' => 43,
                'type' => 0,
                'status' => true,
                'is_role_menu' => 1,
                'route_name' => 'admin.deployment-records.index'
                // 'deleted_at' => new DateTime()
            ],
            [
                'id' => 82,
                'name' => 'Thêm mới biên bản triển khai dự án',
                'code' => 'ADD_DEPLOYMENT_RECORD',
                'parent_id' => 80,
                'function_group' => 'biên bản triển khai dự án',
                'related_array_id' => "[81]",
                // '_lft' => 42,
                // '_rgt' => 43,
                'type' => 0,
                'status' => true,
            ],
            [
                'id' => 83,
                'name' => 'Sửa biên bản triển khai dự án',
                'code' => 'EDIT_DEPLOYMENT_RECORD',
                'parent_id' => 80,
                'function_group' => 'biên bản triển khai dự án',
                'related_array_id' => "[81]",
                // '_lft' => 42,
                // '_rgt' => 43,
                'type' => 0,
                'status' => true,
            ],
            [
                'id' => 84,
                'name' => 'Xóa biên bản triển khai dự án',
                'code' => 'DELETE_DEPLOYMENT_RECORD',
                'parent_id' => 80,
                'function_group' => 'biên bản triển khai dự án',
                'related_array_id' => "[81]",
                // '_lft' => 42,
                // '_rgt' => 43,
                'type' => 0,
                'status' => true,
            ],
            [
                'id' => 85,
                'name' => 'Quản lý biên bản nghiệm thu',
                'code' => 'ACCEPTANCE_RECORD',
                'parent_id' => 1,
                'function_group' => 'biên bản nghiệm thu',
                'related_array_id' => "",
                // '_lft' => 42,
                // '_rgt' => 43,
                'type' => 0,
                'status' => true,
            ],
            [
                'id' => 86,
                'name' => 'Xem biên bản nghiệm thu',
                'code' => 'VIEW_ACCEPTANCE_RECORD',
                'parent_id' => 85,
                'function_group' => 'biên bản nghiệm thu',
                'related_array_id' => "",
                // '_lft' => 42,
                // '_rgt' => 43,
                'type' => 0,
                'status' => true,
                'is_role_menu' => 1,
                'route_name' => 'admin.acceptance-records.index'
                // 'deleted_at' => new DateTime()
            ],
            [
                'id' => 87,
                'name' => 'Thêm mới biên bản nghiệm thu',
                'code' => 'ADD_ACCEPTANCE_RECORD',
                'parent_id' => 85,
                'function_group' => 'biên bản nghiệm thu',
                'related_array_id' => "[86]",
                // '_lft' => 42,
                // '_rgt' => 43,
                'type' => 0,
                'status' => true,
            ],
            [
                'id' => 88,
                'name' => 'Sửa biên bản nghiệm thu',
                'code' => 'EDIT_ACCEPTANCE_RECORD',
                'parent_id' => 85,
                'function_group' => 'biên bản nghiệm thu',
                'related_array_id' => "[86]",
                // '_lft' => 42,
                // '_rgt' => 43,
                'type' => 0,
                'status' => true,
            ],
            [
                'id' => 89,
                'name' => 'Xóa biên bản nghiệm thu',
                'code' => 'DELETE_ACCEPTANCE_RECORD',
                'parent_id' => 85,
                'function_group' => 'biên bản nghiệm thu',
                'related_array_id' => "[86]",
                // '_lft' => 42,
                // '_rgt' => 43,
                'type' => 0,
                'status' => true,
            ],
            [
                'id' => 90,
                'name' => 'Quản lý công văn, thông báo',
                'code' => 'DISPATCHES',
                'parent_id' => 1,
                'function_group' => 'công văn, thông báo',
                'related_array_id' => "",
                // '_lft' => 42,
                // '_rgt' => 43,
                'type' => 0,
                'status' => true,
            ],
            [
                'id' => 91,
                'name' => 'Xem công văn, thông báo',
                'code' => 'VIEW_DISPATCHES',
                'parent_id' => 90,
                'function_group' => 'công văn, thông báo',
                'related_array_id' => "",
                // '_lft' => 42,
                // '_rgt' => 43,
                'type' => 0,
                'status' => true,
                'is_role_menu' => 1,
                'route_name' => 'admin.acceptance-records.index'
                // 'deleted_at' => new DateTime()
            ],
            [
                'id' => 92,
                'name' => 'Thêm mới công văn, thông báo',
                'code' => 'ADD_DISPATCHES',
                'parent_id' => 90,
                'function_group' => 'công văn, thông báo',
                'related_array_id' => "[91]",
                // '_lft' => 42,
                // '_rgt' => 43,
                'type' => 0,
                'status' => true,
            ],
            [
                'id' => 93,
                'name' => 'Sửa công văn, thông báo',
                'code' => 'EDIT_DISPATCHES',
                'parent_id' => 90,
                'function_group' => 'công văn, thông báo',
                'related_array_id' => "[91]",
                // '_lft' => 42,
                // '_rgt' => 43,
                'type' => 0,
                'status' => true,
            ],
            [
                'id' => 94,
                'name' => 'Xóa công văn, thông báo',
                'code' => 'DELETE_DISPATCHES',
                'parent_id' => 90,
                'function_group' => 'công văn, thông báo',
                'related_array_id' => "[91]",
                // '_lft' => 42,
                // '_rgt' => 43,
                'type' => 0,
                'status' => true,
            ],
            [
                'id' => 104,
                'name' => 'Admin',
                'code' => 'SYSTEM_ADMIN',
                'parent_id' => null,
                'function_group' => 'admin',
                'related_array_id' => "",
                // '_lft' => 42,
                // '_rgt' => 43,
                'type' => 0,
                'status' => true,
            ],

            [
                'id' => 119,
                'name' => 'Báo cáo',
                'code' => 'REPORT',
                'parent_id' => 1,
                'function_group' => 'báo cáo',
                // '_lft' => 25,
                // '_rgt' => 34,
                'type' => 0,
                'status' => true,
            ],
            [
                'id' => 120,
                'name' => 'Xem báo cáo khách hàng',
                'code' => 'VIEW_CUSTOMER_REPORT',
                'parent_id' => 119,
                'function_group' => 'báo cáo',
                // '_lft' => 26,
                // '_rgt' => 27,
                'type' => 0,
                'status' => true,
                'is_role_menu' => 1,
                'route_name' => 'admin.reports.customers.index'
                // 'deleted_at' => new DateTime()
            ],
            [
                'id' => 121,
                'name' => 'Xem báo cáo dự án',
                'code' => 'VIEW_PROJECT_REPORT',
                'parent_id' => 119,
                'function_group' => 'báo cáo',
                // '_lft' => 26,
                // '_rgt' => 27,
                'type' => 0,
                'status' => true,
                'is_role_menu' => 1,
                'route_name' => 'admin.reports.projects.index'
                // 'deleted_at' => new DateTime()
            ],
            [
                'id' => 122,
                'name' => 'Xem báo cáo hợp đồng',
                'code' => 'VIEW_CONTRACT_REPORT',
                'parent_id' => 119,
                'function_group' => 'báo cáo',
                // '_lft' => 26,
                // '_rgt' => 27,
                'type' => 0,
                'status' => true,
                'is_role_menu' => 1,
                'route_name' => 'admin.reports.contracts.index'
                // 'deleted_at' => new DateTime()
            ],
            [
                'id' => 123,
                'name' => 'Xem báo cáo công văn, thông báo',
                'code' => 'VIEW_DISPATCH_REPORT',
                'parent_id' => 119,
                'function_group' => 'báo cáo',
                // '_lft' => 26,
                // '_rgt' => 27,
                'type' => 0,
                'status' => true,
                'is_role_menu' => 1,
                'route_name' => 'admin.reports.dispatches.index'
                // 'deleted_at' => new DateTime()
            ],
            [
                'id' => 124,
                'name' => 'Xem báo cáo tiến độ thanh toán hợp đồng',
                'code' => 'VIEW_PAYMENT_CONTRACT_REPORT',
                'parent_id' => 119,
                'function_group' => 'báo cáo',
                // '_lft' => 26,
                // '_rgt' => 27,
                'type' => 0,
                'status' => true,
                'is_role_menu' => 1,
                'route_name' => 'admin.reports.payment-details.index'
                // 'deleted_at' => new DateTime()
            ],
            [
                'id' => 125,
                'name' => 'Xem báo cáo tiến độ nghiệm thu',
                'code' => 'VIEW_ACCEPTANCE_REPORT',
                'parent_id' => 119,
                'function_group' => 'báo cáo',
                // '_lft' => 26,
                // '_rgt' => 27,
                'type' => 0,
                'status' => true,
                'is_role_menu' => 1,
                'route_name' => 'admin.reports.acceptance-records.index'
                // 'deleted_at' => new DateTime()
            ],
            [
                'id' => 126,
                'name' => 'Xem báo cáo tiến độ triển khai',
                'code' => 'VIEW_DEPLOYMENT_REPORT',
                'parent_id' => 119,
                'function_group' => 'báo cáo',
                // '_lft' => 26,
                // '_rgt' => 27,
                'type' => 0,
                'status' => true,
                'is_role_menu' => 1,
                'route_name' => 'admin.reports.deployment-records.index'
                // 'deleted_at' => new DateTime()
            ],
            // id hiện có = 136
        ];
        foreach ($functions as $function) {
            SystemFunction::create($function);
            // DB::table('system_functions')->insert($function);
        }
    }
}
